language: go
sudo: false
dist: trusty
go:
    - "1.11.4"
script:
- ".travis/make all"
deploy:
  - provider: script
    skip_cleanup: true
    script: ".travis/make build upload"
    on:
      tags: true
