[pre_start]
  cmd = "sleep 2"
  user = "www-data"

[[process]]
  cmd = "sleep 60"
  user = "www-data"

[[process]]
  cmd = "sleep 60"
  user = "dz0ny"

[post_start]
  cmd = "sleep 20"
  user = "www-data"