[pre_start]
  cmd = "sleep 2"
  user = "www-data"

[[process]]
  cmd = "sleep 60"
  user = "www-data"

[[process]]
  cmd = "sleep 60"
  user = "dz0ny"

[post_start]
  cmd = "sleep 20"
  user = "www-data"

[[cron]]
  schedule = "@every 5s"
  [cron.job]
    cmd = "echo tick5"
    user = "www-data"

[[cron]]
  schedule = "@every 15s"
  [cron.job]
    cmd = "echo tick15"
    user = "www-data"
