[pre_start]
  cmd = "sleep 2"
  user = "www-data"

[[process]]
  cmd = "sleep 10"
  user = "www-data"

[[process]]
  cmd = "sleep 15"
  user = "dz0ny"

[[process]]
  cmd = "sleep 33"
  user = "dz0ny"
  [process.enabled]
    operator="EnvEqual"
    key= "PHP_RUNTIME"
    value="php73"

[post_start]
  cmd = "sleep 4"
  user = "www-data"

[[cron]]
  schedule = "@every 5s"
  [cron.job]
    cmd = "echo tick5"
    user = "www-data"

[[cron]]
  schedule = "@every 6s"
  [cron.job]
    cmd = "sh -c 'exit'"
    user = "www-data"
