[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.1.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[override]]
  name = "github.com/golangci/golangci-lint"
  version = "1.10.2"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/copier"
